# Generated by Django 5.2.1 on 2025-07-23 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_file_comment_alter_file_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='comment',
            field=models.TextField(blank=True, max_length=500, validators=[django.core.validators.RegexValidator(message='Комментарий содержит недопустимые символы.', regex='^[\\w\\s\\-\\.\\(\\)\\[\\]!@#$%^&+=;,\\\'\\"]*')], verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='file',
            name='original_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Имя файла содержит недопустимые символы.', regex="^[\\w\\s\\-\\.\\(\\)\\[\\]!@#$%^&+=;,\\']+")], verbose_name='original filename'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Введите корректный email.', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+')], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Полное имя может содержать только буквы, пробелы и дефисы.', regex='^[a-zA-Zа-яА-ЯёЁ\\s\\-]+')], verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Обязательное поле. 4-20 символов. Только буквы и цифры. Первый символ — буква.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Username должен начинаться с буквы, содержать только буквы и цифры, длина 4-20 символов.', regex='^[a-zA-Z][a-zA-Z0-9]{3,19}')], verbose_name='username'),
        ),
    ]
