# Generated by Django 5.2.1 on 2025-10-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_file_comment_alter_file_original_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indicates if the file has been deleted', verbose_name='is deleted'),
        ),
    ]
